#' Plot a Venn Diagram from Genomic or Set Overlap Results
#'
#' This function creates a Venn diagram using the `eulerr` package to visualize
#' intersections across multiple sets. Supports both
#' `GenomicOverlapResult` and `SetOverlapResult` objects.
#'
#' @param overlap_object A `GenomicOverlapResult` or `SetOverlapResult` object
#'   returned by \code{\link{computeOverlaps}}.
#' @param fills Controls the fill appearance of the diagram. Can be:
#'   \itemize{
#'     \item \strong{logical}: `TRUE` (default) shows fills, `FALSE` hides them
#'     \item \strong{character vector}: Colors for the fills.
#'     Default colors are: c("#2B70AB", "#FFB027", "#3EA742", "#CD3301", "#9370DB",
#'     "#008B8B", "#D87093", "#C7C4FC", "#FCBAA3", "#187EFA", "#CFCE64", "#527346",
#'     "#F8B6D8", "#AB80C5", "#B99074"). One color is used per region of the
#'     diagram, so a two-set diagram uses the first three, a three-set diagram the
#'     first seven, and a four-set diagram all fifteen.
#'     \item \strong{list}: Fine control with graphical parameters including
#'       `fill` (colors), `alpha` (transparency 0-1)
#'   }
#' @param edges Controls the edge/border appearance. Can be:
#'   \itemize{
#'     \item \strong{logical}: `TRUE` (default) shows edges, `FALSE` hides them
#'     \item \strong{character vector}: Colors for the edges
#'     \item \strong{list}: Fine control with `col` (colors), `alpha` (transparency 0-1),
#'       `lty` (line type), `lwd` (line width), `lex` (line expansion)
#'   }
#' @param labels Controls set labels. Can be:
#'   \itemize{
#'     \item \strong{logical}: `TRUE` shows default labels, `FALSE` hides them
#'     \item \strong{character vector}: Custom text for labels
#'     \item \strong{list}: Fine control with `col` (text color), `fontsize`,
#'       `font` (1=plain, 2=bold, 3=italic, 4=bold italic), `fontfamily`,
#'       `cex` (character expansion), `alpha` (transparency 0-1)
#'   }
#' @param quantities Controls intersection quantities display. Can be:
#'   \itemize{
#'     \item \strong{logical}: `TRUE` shows counts, `FALSE` hides them
#'     \item \strong{character vector}: Custom text labels
#'     \item \strong{list}: Fine control with `type` (c("counts", "percent")),
#'       `col` (text color), `fontsize`, `font`, `fontfamily`, `cex`, `alpha`
#'   }
#' @param legend Controls the legend. Can be:
#'   \itemize{
#'     \item \strong{logical}: `FALSE` to disable
#'     \item \strong{character}: Position ("right", "top", "bottom", "left")
#'     \item \strong{list}: Fine control with `side` (position), `labels`
#'       (custom labels), `col`, `fontsize`, `cex`, `fontfamily`
#'   }
#' @param main Title for the plot. Can be character, expression, or list with
#'   `label` (text), `col`, `fontsize`, `font`, `fontfamily`
#' @param verbose Logical. If `TRUE` (default), a message reporting
#'   `eulerr`'s `diagError` is emitted for every diagram, regardless of the
#'   number of sets, together with whether it falls above or below the
#'   threshold of 1e-6 below which Micallef and Rodgers (2014) call a diagram
#'   accurately proportional to the data it depicts. When the fit leaves a
#'   populated region with no area at all, the message also names those
#'   regions; a diagram can lose a region while `diagError` stays small, since
#'   `diagError` is a proportion of the whole diagram and so is insensitive to
#'   small regions being erased.
#'   Set to `FALSE` to silence this message. All four
#'   diagnostics are always attached to the returned object regardless of
#'   `verbose` (see `Value`).
#' @param ... Additional arguments passed to \code{\link[eulerr]{plot.euler}}.
#'
#' @return A Venn diagram plot generated by \code{eulerr}. The
#'   goodness-of-fit diagnostics are attached as a `"fit_diagnostics"`
#'   attribute, a list with elements `stress`, `diagError`, `regionError`
#'   and `undrawnRegions`. For both `stress` and `diagError`, `0` indicates a
#'   perfect fit and larger values indicate a greater geometric distortion;
#'   `diagError` is the largest discrepancy, over all regions, between the
#'   share of the total diagram area a region is given and the share the data
#'   requires, a proportion in \eqn{[0, 1]}. Micallef and Rodgers (2014), who
#'   introduced it, call a diagram accurately proportional to its data when
#'   `diagError` is at most 1e-6, the threshold this function reports against.
#'   See
#'   \code{\link[eulerr]{euler}} for the exact definitions of the first
#'   three. `undrawnRegions` is a character vector naming the regions that
#'   the data populates but the diagram gives no area to; it is empty for a
#'   faithful diagram. Retrieve them all with `attr(venn, "fit_diagnostics")`.
#'   The `eulerr` fit itself is attached as an `"euler_fit"` attribute.
#' @export
#'
#' @seealso \code{\link{plotVennError}} to see which regions the diagram
#'   misrepresents and in which direction, \code{\link{plotUpSet}}.
#'
#' @examples
#' # Example with gene sets
#' data(gene_list)
#' res_sets <- computeOverlaps(gene_list)
#'
#' # Basic plot
#' plotVenn(res_sets)
#'
#' # Customize fills with transparency and custom colors
#' plotVenn(res_sets,
#'          fills = list(fill = c("#FF6B6B", "#4ECDC4", "#45B7D1"),
#'                       alpha = 0.6))
#'
#' # Customize edges
#' plotVenn(res_sets,
#'          edges = list(col = "darkgray", lwd = 2, lty = 2))
#'
#' # Customize labels
#' plotVenn(res_sets,
#'          labels = list(col = "white", font = 2, fontsize = 14))
#'
#' # Show both counts and percentages
#' plotVenn(res_sets,
#'          quantities = list(type = c("counts", "percent"),
#'                           col = "black", fontsize = 10))
#'
#' # Add a title
#' plotVenn(res_sets,
#'          main = list(label = "Gene Set Overlaps",
#'                      col = "navy", fontsize = 16, font = 2))
#'
#' # Transparent fills with colored borders only
#' plotVenn(res_sets,
#'          fills = "transparent",
#'          edges = list(col = c("red", "blue", "green"), lwd = 3))
#'
#' # Custom legend
#' plotVenn(res_sets,
#'          legend = list(side = "bottom",
#'                       labels = c("Treatment A", "Treatment B", "Control"),
#'                       fontsize = 12))
#'
#' # Inspect eulerr's fit diagnostics (stress, diagError, regionError)
#' venn <- plotVenn(res_sets)
#' attr(venn, "fit_diagnostics")
plotVenn <- function(overlap_object,
                     fills = TRUE,
                     edges = TRUE,
                     labels = FALSE,
                     quantities = list(type = "counts"),
                     legend = "right",
                     main = NULL,
                     verbose = TRUE,
                     ...) {

    # Check input object class
    if (!inherits(overlap_object, "GenomicOverlapResult") &&
        !inherits(overlap_object, "SetOverlapResult")) {
        stop("Input must be a GenomicOverlapResult or SetOverlapResult.")
    }

    # Extract matrix
    overlap_matrix <- overlap_object[["overlap_matrix"]]

    # Compute Euler fit.
    # Two sets are always represented exactly by two circles, and the two extra
    # parameters an ellipse carries buy nothing there while opening local minima
    # the optimizer can settle in, erasing the intersection outright. Ellipses
    # are still needed from three sets on.
    fit <- eulerr::euler(
        overlap_matrix,
        shape = if (ncol(overlap_matrix) == 2) "circle" else "ellipse"
    )

    # Number of subsets as defined by eulerr: every region of the diagram
    # (2^n_sets - 1), regardless of whether each region is populated.
    n_subset <- length(fit$original.values)

    # Process fills parameter
    if (is.logical(fills) && fills == TRUE) {
        # eulerr requires fills length to be 1, n_sets, or n_subsets;
        # recycle defaults to n_subset so every region gets a color.
        default_colors <- c("#2B70AB", "#FFB027", "#3EA742", "#CD3301",
                            "#9370DB", "#008B8B", "#D87093",
                            "#C7C4FC", "#FCBAA3", "#187EFA", "#CFCE64",
                            "#527346", "#F8B6D8", "#AB80C5", "#B99074")
        fills <- rep_len(default_colors, n_subset)
    } else if (is.character(fills) && length(fills) == 1 && fills == "transparent") {
        # Handle "transparent" as special case
        fills <- "transparent"
    } else if (is.character(fills)) {
        # User provided colors as vector
        fills <- fills
    }
    # If fills is already a list or FALSE, pass through as-is

    # Process edges parameter
    if (is.logical(edges) && edges == TRUE) {
        # Default edges settings
        edges <- list(alpha = 0)  # Default to invisible edges when fills are used
    }
    # If edges is already a list, character vector, or FALSE, pass through as-is

    # Process legend parameter
    if (is.character(legend)) {
        # Convert position string to list format
        legend <- list(side = legend)
    } else if (is.logical(legend) && legend == FALSE) {
        legend <- FALSE
    }
    # If legend is already a list, pass through as-is

    # Validate quantities type when it's a list
    if (is.list(quantities) && !is.null(quantities$type)) {
        ok <- c("counts", "percent")
        qt <- as.character(quantities$type)
        if (!all(qt %in% ok) || length(qt) > 2) {
            stop("`quantities$type` must be a vector of 'counts' and/or ",
                 "'percent' (max length 2).")
        }
    }

    # Plot the diagram
    venn <- plot(
        fit,
        fills = fills,
        edges = edges,
        labels = labels,
        quantities = quantities,
        legend = legend,
        main = main,
        ...
    )

    # Attach goodness-of-fit diagnostics to the returned object so
    # users can check how well the diagram approximates the input, e.g. for
    # 4+-set diagrams where the elliptical fit is more constrained.
    # `undrawn` is the regions the data populates that the diagram gives no
    # area to at all.
    undrawn <- names(fit$original.values)[
        fit$original.values > 0 & fit$fitted.values <= .Machine$double.eps
    ]

    fit_diagnostics <- list(
        stress = fit$stress,
        diagError = fit$diagError,
        regionError = fit$regionError,
        undrawnRegions = undrawn
    )
    attr(venn, "fit_diagnostics") <- fit_diagnostics

    # The fit itself, so that plotVennError() can shade exactly the diagram
    # drawn here.
    attr(venn, "euler_fit") <- fit

    if (isTRUE(verbose)) {
        diag_error_threshold <- 1e-6
        over <- fit_diagnostics$diagError > diag_error_threshold

        paint <- function(x, colour) {
            if (!requireNamespace("cli", quietly = TRUE)) return(x)
            switch(colour,
                   red   = cli::col_red(x),
                   green = cli::col_green(x),
                   bold  = cli::style_bold(x),
                   x)
        }
        bad <- over || length(undrawn) > 0
        verdict_colour <- if (bad) "red" else "green"

        message(
            paint(sprintf("%s Venn diagError = %.3e  (%s %s)\n",
                          if (bad) "\u2718" else "\u2714",
                          fit_diagnostics$diagError,
                          if (over) ">" else "<=",
                          format(diag_error_threshold)),
                  verdict_colour),
            if (length(undrawn) > 0) {
                paint(sprintf("  %d of %d regions %s no area at all: %s\n",
                              length(undrawn), length(fit$original.values),
                              if (length(undrawn) == 1) "is given" else "are given",
                              paste(undrawn, collapse = ", ")),
                      "red")
            } else {
                ""
            },
            "  Access fit diagnostics with attr(<plotVenn output>, \"fit_diagnostics\")"
        )
    }

    return(venn)
}
