#' Plot a Venn Diagram from Genomic or Set Overlap Results
#'
#' This function creates a Venn diagram using the `eulerr` package to visualize intersections
#' across multiple sets (up to ~5). Supports both `GenomicOverlapsResult` and `SetOverlapsResult` objects.
#'
#' @param overlap_object A `GenomicOverlapsResult` or `SetOverlapsResult` object returned by
#'   \code{\link{computeOverlaps}}.
#' @param labels Logical. Whether to show set labels on the diagram. Default is `FALSE`.
#' @param legend Position of the legend ("right", "top", "bottom", etc.) or `FALSE` to disable.
#' @param fill A character vector of fill colors for the sets.
#' @param ... Additional arguments passed to \code{\link[eulerr]{plot.euler}}.
#'
#' @return A Venn diagram plot generated by \code{eulerr}.
#' @export
#'
#' @examples
#' # Example with gene sets (built-in dataset)
#' data(gene_list)
#' res_sets <- computeOverlaps(gene_list)
#' plotVenn(res_sets)
#'
#' # Example with genomic regions (built-in dataset)
#' data(a549_chipseq_peaks)
#' res_genomic <- computeOverlaps(a549_chipseq_peaks)
#' plotVenn(res_genomic)
plotVenn <- function(overlap_object,
                     labels = FALSE,
                     legend = "right",
                     fill = c("#2B70AB", "#FFB027", "#3EA742", "#CD3301", "#9370DB"),
                     ...) {
    # Check input object class
    if (!inherits(overlap_object, "GenomicOverlapResult") &&
        !inherits(overlap_object, "SetOverlapResult")) {
        stop("Input must be a GenomicOverlapResult or SetOverlapResult.")
    }

    # Extract matrix
    overlap_matrix <- overlap_object[["overlap_matrix"]]

    # Compute Euler fit
    fit <- eulerr::euler(overlap_matrix, shape = "ellipse")

    # Plot
    venn <- plot(
        fit,
        labels = labels,
        legend = if (isFALSE(legend)) FALSE else list(side = legend),
        quantities = list(type = "counts"),
        fills = fill,
        edges = list(alpha = 0),
        ...
    )
    return(venn)
}
