#' Plot an UpSet Diagram from Genomic or Set Overlap Results
#'
#' This function creates an UpSet plot using the `ComplexHeatmap` package to
#' visualize intersections across multiple sets.
#' Supports both `GenomicOverlapsResult` and `SetOverlapsResult` objects.
#'
#' @param overlap_object A `GenomicOverlapsResult` or `SetOverlapsResult` object
#' returned by \code{\link{computeOverlaps}}.
#'
#' @return An UpSet plot object generated by \code{ComplexHeatmap::UpSet}.
#' @export
#'
#' @examples
#' # Example with SetOverlapsResult
#' gene_sets <- list(
#'   TF1 = c("TP53", "BRCA1", "MYC", "GATA3", "FOXA1"),
#'   TF2 = c("MYC", "ESR1", "GATA3", "FOXA1", "AR"),
#'   TF3 = c("TP53", "GATA3", "AR", "NANOG", "SOX2")
#' )
#' res_sets <- computeOverlaps(gene_sets)
#' plotUpSet(res_sets)
#'
#' # Example with GenomicOverlapsResult
#' gr1 <- GenomicRanges::GRanges("chr1", IRanges::IRanges(c(100, 500, 900), width = 100))
#' gr2 <- GenomicRanges::GRanges("chr1", IRanges::IRanges(c(150, 520, 1000), width = 100))
#' gr3 <- GenomicRanges::GRanges("chr1", IRanges::IRanges(c(300, 550, 1100), width = 100))
#' peak_sets <- list(H3K27ac = gr1, MED1 = gr2, BRD4 = gr3)
#' res_genomic <- computeOverlaps(peak_sets)
#' plotUpSet(res_genomic)
plotUpSet <- function(overlap_object) {
    if (!inherits(overlap_object, "GenomicOverlapResult") &&
        !inherits(overlap_object, "SetOverlapResult")) {
        stop("Input must be a GenomicOverlapResult or SetOverlapResult.")
    }

    overlap_matrix <- overlap_object[["overlap_matrix"]]
    combMat <- ComplexHeatmap::make_comb_mat(overlap_matrix)

    annot_top <- ComplexHeatmap::HeatmapAnnotation(
        "Intersection\nsize" = ComplexHeatmap::anno_barplot(
            ComplexHeatmap::comb_size(combMat),
            border = FALSE,
            gp = grid::gpar(fill = "black"),
            height = grid::unit(1.25, "cm")
        ),
        "Size" = ComplexHeatmap::anno_text(
            ComplexHeatmap::comb_size(combMat),
            rot = 0,
            just = "center",
            location = 0.25
        ),
        annotation_name_side = "left",
        annotation_name_rot = 0
    )

    annot_right <- ComplexHeatmap::rowAnnotation(
        "Set size" = ComplexHeatmap::anno_barplot(
            ComplexHeatmap::set_size(combMat),
            border = FALSE,
            gp = grid::gpar(fill = "black"),
            width = grid::unit(1.25, "cm")
        ),
        "Size" = ComplexHeatmap::anno_text(ComplexHeatmap::set_size(combMat))
    )

    upset <- ComplexHeatmap::UpSet(
        combMat,
        top_annotation = annot_top,
        right_annotation = annot_right
    )

    return(upset)
}
