#' Plot an UpSet Diagram from Genomic or Set Overlap Results
#'
#' This function creates an UpSet plot using the `ComplexHeatmap` package to
#' visualize intersections across multiple sets.
#' Supports both `GenomicOverlapsResult` and `SetOverlapsResult` objects.
#'
#' @param overlap_object A `GenomicOverlapsResult` or `SetOverlapsResult` object
#' returned by \code{\link{computeOverlaps}}.
#'
#' @return An UpSet plot object generated by \code{ComplexHeatmap::UpSet}.
#' @export
#'
#' @examples
#' # Example with gene sets (built-in dataset)
#' data(gene_list)
#' res_sets <- computeOverlaps(gene_list)
#' plotUpSet(res_sets)
#'
#' # Example with genomic regions (built-in dataset)
#' data(a549_chipseq_peaks)
#' res_genomic <- computeOverlaps(a549_chipseq_peaks)
#' plotUpSet(res_genomic)
plotUpSet <- function(overlap_object) {
    if (!inherits(overlap_object, "GenomicOverlapResult") &&
        !inherits(overlap_object, "SetOverlapResult")) {
        stop("Input must be a GenomicOverlapResult or SetOverlapResult.")
    }

    overlap_matrix <- overlap_object[["overlap_matrix"]]
    combMat <- ComplexHeatmap::make_comb_mat(overlap_matrix)

    annot_top <- ComplexHeatmap::HeatmapAnnotation(
        "Intersection\nsize" = ComplexHeatmap::anno_barplot(
            ComplexHeatmap::comb_size(combMat),
            border = FALSE,
            gp = grid::gpar(fill = "black"),
            height = grid::unit(1.25, "cm")
        ),
        "Size" = ComplexHeatmap::anno_text(
            ComplexHeatmap::comb_size(combMat),
            rot = 0,
            just = "center",
            location = 0.25
        ),
        annotation_name_side = "left",
        annotation_name_rot = 0
    )

    annot_right <- ComplexHeatmap::rowAnnotation(
        "Set size" = ComplexHeatmap::anno_barplot(
            ComplexHeatmap::set_size(combMat),
            border = FALSE,
            gp = grid::gpar(fill = "black"),
            width = grid::unit(1.25, "cm")
        ),
        "Size" = ComplexHeatmap::anno_text(ComplexHeatmap::set_size(combMat))
    )

    upset <- ComplexHeatmap::UpSet(
        combMat,
        top_annotation = annot_top,
        right_annotation = annot_right
    )

    return(upset)
}
