#' Plot a Venn Diagram from Genomic or Set Overlap Results
#'
#' This function creates a Venn diagram using the `eulerr` package to visualize intersections
#' across multiple sets (up to ~5). Supports both `GenomicOverlapsResult` and `SetOverlapsResult` objects.
#'
#' @param overlap_object A `GenomicOverlapsResult` or `SetOverlapsResult` object returned by
#'   \code{\link{computeOverlaps}}.
#' @param labels Logical. Whether to show set labels on the diagram. Default is `FALSE`.
#' @param legend Position of the legend ("right", "top", "bottom", etc.) or `FALSE` to disable.
#' @param fill A character vector of fill colors for the sets.
#' @param ... Additional arguments passed to \code{\link[eulerr]{plot.euler}}.
#'
#' @return A Venn diagram plot generated by \code{eulerr}.
#' @export
#'
#' @examples
#' # Example with SetOverlapResult
#' gene_sets <- list(
#'   TF1 = c("TP53", "BRCA1", "MYC", "GATA3", "FOXA1"),
#'   TF2 = c("MYC", "ESR1", "GATA3", "FOXA1", "AR"),
#'   TF3 = c("TP53", "GATA3", "AR", "NANOG", "SOX2")
#' )
#' res_sets <- computeOverlaps(gene_sets)
#' plotVenn(res_sets)
#'
#' # Example with GenomicOverlapsResult
#' gr1 <- GenomicRanges::GRanges("chr1", IRanges::IRanges(c(100, 500, 900), width = 100))
#' gr2 <- GenomicRanges::GRanges("chr1", IRanges::IRanges(c(150, 520, 1000), width = 100))
#' gr3 <- GenomicRanges::GRanges("chr1", IRanges::IRanges(c(300, 550, 1100), width = 100))
#' peak_sets <- list(H3K27ac = gr1, MED1 = gr2, BRD4 = gr3)
#' res_genomic <- computeOverlaps(peak_sets)
#' plotVenn(res_genomic)
plotVenn <- function(overlap_object,
                     labels = FALSE,
                     legend = "right",
                     fill = c("#2B70AB", "#FFB027", "#3EA742", "#CD3301", "#9370DB"),
                     ...) {
    # Check input object class
    if (!inherits(overlap_object, "GenomicOverlapResult") &&
        !inherits(overlap_object, "SetOverlapResult")) {
        stop("Input must be a GenomicOverlapResult or SetOverlapResult.")
    }

    # Extract matrix
    overlap_matrix <- overlap_object[["overlap_matrix"]]

    # Compute Euler fit
    fit <- eulerr::euler(overlap_matrix, shape = "ellipse")

    # Plot
    venn <- plot(
        fit,
        labels = labels,
        legend = if (isFALSE(legend)) FALSE else list(side = legend),
        quantities = list(type = "counts"),
        fills = fill,
        edges = list(alpha = 0),
        ...
    )
    return(venn)
}
