#' Save a Visualization to File (PDF, PNG, or SVG)
#'
#' This function saves a visualization object to a file in the specified
#' format and directory. It supports visualizations generated by
#' `plotVenn()`, `plotUpSet()`, `ggplot2`, or any other plot object that
#' can be rendered using `print()` inside a graphics device. Optionally,
#' the current date (stored in the `today` variable) can be prepended to
#' the filename.
#'
#' @param viz A visualization object typically created by either
#'   `plotVenn()` or `plotUpSet()`, but can also be a `ggplot2` plot or
#'   any other plot object printable with `print()`.
#' @param output_dir A string specifying the output directory. Defaults
#'   to `"."`.
#' @param output_file A string specifying the base filename (without
#'   extension). Defaults to `"viz_genomicVenn"`.
#' @param format Output format. One of `"pdf"`, `"png"`, or `"svg"`.
#'   Defaults to `"pdf"`.
#' @param with_date Logical (default `TRUE`). Whether to prepend the
#'   current date (from `today`) to the filename.
#' @param width Width of the output file in inches. Default is 5.
#' @param height Height of the output file in inches. Default is 5.
#' @param resolution Resolution in DPI (only used for PNG). Default is
#'   300.
#' @param verbose Logical. If `TRUE`, print a message with the saved
#'   path. Default `TRUE`.
#'
#' @return The visualization is saved to a file on disk. Invisibly
#'   returns the full path to the saved file.
#' @export
#'
#' @examples
#' \dontrun{
#'   # Example with ggplot2
#'   library(ggplot2)
#'   p <- ggplot(mtcars, aes(mpg, wt)) + geom_point()
#'   saveViz(p, output_dir = "viz_example_genomicVenn", output_file = "scatter_plot")
#'
#'   # Example with Venn plot using 3 ChIP-seq-like GRanges with 1000 peaks each
#'   set.seed(123)
#'   gr1 <- GenomicRanges::GRanges(
#'     seqnames = sample(c("chr1", "chr2"), 1000, replace = TRUE),
#'     ranges = IRanges::IRanges(start = sample(1:1e6, 1000), width = 150)
#'   )
#'
#'   gr2 <- GenomicRanges::GRanges(
#'     seqnames = sample(c("chr1", "chr2"), 1000, replace = TRUE),
#'     ranges = IRanges::IRanges(start = sample(1:1.5e6, 1000), width = 150)
#'   )
#'
#'   gr3 <- GenomicRanges::GRanges(
#'     seqnames = sample(c("chr1", "chr2"), 1000, replace = TRUE),
#'     ranges = IRanges::IRanges(start = sample(1:2e6, 1000), width = 150)
#'   )
#'
#'   peaklist <- list(H3K27ac = gr1, ZNF768 = gr2, EP300 = gr3)
#'   overlap <- computeOverlaps(peaklist)
#'   venn_plot <- plotVenn(overlap)
#'   saveViz(venn_plot, output_dir = "viz_example_genomicVenn", output_file = "venn_example")
#'
#'   # Example with UpSet plot
#'   upset_plot <- plotUpSet(overlap)
#'   saveViz(upset_plot, output_dir = "viz_example_genomicVenn", output_file = "upset_example")
#'
#'   # Save to PNG instead of PDF
#'   saveViz(upset_plot, format = "png", output_file = "upset_example_png", height = 2.5)
#'
#'   # Save to SVG
#'   saveViz(venn_plot, format = "svg", output_file = "venn_example_svg")
#' }
saveViz <- function(viz,
                    output_dir = ".",
                    output_file = "figure_genomicVenn",
                    format = "pdf",
                    with_date = TRUE,
                    width = 5,
                    height = 5,
                    resolution = 300,
                    verbose = TRUE) {
    format <- match.arg(format, choices = c("pdf", "png", "svg"))

    if (!dir.exists(output_dir)) {
        dir.create(output_dir, recursive = TRUE)
    }

    if (isTRUE(with_date)) {
        output_file <- paste0(today, "_", output_file)
    }

    filepath <- file.path(output_dir, paste0(output_file, ".", format))

    switch(format,
           pdf = grDevices::pdf(file = filepath, width = width, height = height),
           png = grDevices::png(file = filepath, width = width, height = height, units = "in", res = resolution),
           svg = grDevices::svg(file = filepath, width = width, height = height))

    print(viz)
    grDevices::dev.off()

    if (isTRUE(verbose)) {
        message(" > Visualization (", format, ") saved in ", filepath)
    }
    invisible(filepath)
}
